#!/bin/sh

#SBATCH --job-name=CSBnB

#SBATCH --output=CSBnB.o

#SBATCH --error=CSBnB.error

#SBATCH --partition=savio

#SBATCH --time=400:00:00

#SBATCH --nodes=1

#SBATCH --ntasks-per-node=20

#SBATCH --cpus-per-task=1

# QoS:

#SBATCH --qos=nuclear_savio_normal

#

# Account:

#SBATCH -A co_nuclear

#SBATCH --mail-user=keckler@berkeley.edu
#SBATCH --mail-type=all

# run command

~/bin/sss2/sss2_mpi -omp 20 CSBnB